"""data_adapter.py — lead_subset → ultralytics data.yaml 适配。

职责（单一）：
    生成 ultralytics 训练所需的 data.yaml，指向 lead_subset 数据集。
    ultralytics 期望 YOLO txt 格式（与 lead_subset 现有格式一致）。

不负责：
    - 数据集本身（由 prepare_lead_dataset.py 产出）
    - 训练（由 yolo11_builder.py / ultralytics trainer）
"""
from __future__ import annotations

from pathlib import Path


# lead_subset 的 7 类（与 configs/lead_subset.yaml 一致）
CLASS_NAMES = ["person", "bicycle", "car", "backpack", "suitcase", "chair", "bottle"]

DATA_YAML_CONTENT = """\
# LEAD-Net 7-class subset for ultralytics training
# Auto-generated by lead_net/models/yolo/data_adapter.py
path: {dataset_root}
train: images/train
val: images/val
test: images/val  # 用 val 作 test（KITTI 独立 test 留后续）

names:
  0: person
  1: bicycle
  2: car
  3: backpack
  4: suitcase
  5: chair
  6: bottle
"""


def write_data_yaml(dataset_root: str | Path, out_path: str | Path) -> Path:
    """生成 ultralytics data.yaml。

    Args:
        dataset_root: lead_subset 根目录（含 images/train, images/val, labels/）
        out_path: 输出 yaml 路径
    Returns:
        写入的 yaml 路径
    """
    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    # 用绝对路径避免 ultralytics 工作目录歧义
    root_abs = Path(dataset_root).resolve().as_posix()
    out.write_text(DATA_YAML_CONTENT.format(dataset_root=root_abs), encoding="utf-8")
    return out


if __name__ == "__main__":
    out = write_data_yaml("data/lead_subset", "configs/lead_subset_ultralytics.yaml")
    print(f"data.yaml written to {out}")
